server:
  port: 8080
spring:
  datasource:
    url: 'jdbc:h2:mem:test'
    username: sa
    password:
    driver-class-name: org.h2.Driver
  profiles:
    active: local
  application:
    name: 'sse-practice'
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  h2:
    console:
      enabled: true
      path: '/h2-console'
  jpa:
    open-in-view: false